# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= linux-gnu
MACHINETYPE	:= x86_64
PLATFORM	:= x86_64-unknown-linux-gnu
FULLOSTYPE	:= unknown-linux-gnu
